packages:
  - frontend/plugin
  - test-app/frontend

allowBuilds:
  "@carbon/charts": true
  "@carbon/colors": true
  "@carbon/feature-flags": true
  "@carbon/grid": true
  "@carbon/icons": true
  "@carbon/layout": true
  "@carbon/motion": true
  "@carbon/styles": true
  "@carbon/themes": true
  "@carbon/type": true
  "@carbon/utils-position": true
  "@parcel/watcher": true
  "@scarf/scarf": true
  "@tree-sitter-grammars/tree-sitter-yaml": true
  carbon-components-angular: true
  core-js: true
  core-js-pure: true
  esbuild: true
  inferno: true
  less: true
  lmdb: true
  msgpackr-extract: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
