{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valtimo-demo.backend.fullname" . }}
  labels:
    {{- include "valtimo-demo.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  keycloak-client-secret: {{ include "valtimo-demo.keycloakClientSecret" . | quote }}
  plugin-encryption-secret: {{ include "valtimo-demo.pluginEncryptionSecret" . | quote }}
  operaton-admin-password: {{ include "valtimo-demo.operatonAdminPassword" . | quote }}
  {{- if .Values.keycloak.enabled }}
  keycloak-admin-password: {{ include "valtimo-demo.keycloak.adminPassword" . | quote }}
  {{- end }}
  {{- if or .Values.epistola.enabled .Values.externalEpistola.url }}
  epistola-client-secret: {{ include "valtimo-demo.epistolaClientSecret" . | quote }}
  {{- end }}
{{- end }}
