apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valtimo-demo.backend.fullname" . }}
  labels:
    {{- include "valtimo-demo.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  keycloak-client-secret: {{ .Values.backend.keycloak.backendClientSecret | quote }}
  plugin-encryption-secret: {{ .Values.backend.valtimo.pluginEncryptionSecret | quote }}
  operaton-admin-password: {{ .Values.backend.operaton.adminPassword | quote }}
  {{- if .Values.keycloak.enabled }}
  keycloak-admin-password: {{ include "valtimo-demo.keycloak.adminPassword" . | quote }}
  {{- end }}
