{{- if and (eq .Values.database.type "cnpg") (eq (include "valtimo-demo.keycloak.enabled" .) "true") }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "valtimo-demo.cnpg.clusterName" . }}-keycloak
  labels:
    {{- include "valtimo-demo.labels" . | nindent 4 }}
spec:
  name: keycloak
  owner: {{ .Values.database.cnpg.owner }}
  cluster:
    name: {{ include "valtimo-demo.cnpg.clusterName" . }}
{{- end }}
