spring:
  autoconfigure:
    exclude:
      - com.valtimo.keycloak.autoconfigure.KeycloakAutoConfiguration
      - com.valtimo.keycloak.autoconfigure.ExternalRoleAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OIDC_JWKS_URI}
      client:
        provider:
          keycloakjwt:
            issuer-uri: ${OIDC_ISSUER_URI}
          keycloakapi:
            issuer-uri: ${OIDC_ISSUER_URI}
        registration:
          keycloakjwt:
            client-id: ${OIDC_CLIENT_ID:valtimo-console}
          keycloakapi:
            client-id: ${OIDC_BACKEND_CLIENT_ID:valtimo-backend}
            client-secret: ${OIDC_BACKEND_CLIENT_SECRET}
            authorization-grant-type: client_credentials

valtimo:
  keycloak:
    client: ${OIDC_CLIENT_ID:valtimo-console}
